### ISSUE TITLE
Неверное отображение названия ставки в классе CreditAccount при использовании метода IllegalArgumentException.

### ISSUE THREAD

**Issue by GKZ28** [GKZ28/Java_Diplom#1]
# Описание
Отображается неверное название ставки в методе.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L22

# Предусловия
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Запустить программу

# Шаги воспроизведения
1. Создать объект класса **CreditAccount** cо значение **rate** меньше 0.

# Результаты
*Ожидаемый :* "**Кредитная** ставка не может быть ..."
*Фактический :* "**Накопительная** ставка не может быть ..."

# Локация теста
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L73

# Окружение
* **Операционная система.** Windows 11
*  **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Gamidov-M** [comment]
Скорректировал
https://github.com/GKZ28/Java_Diplom/blob/c0039adbcd225eaa4b36e1cbb9d085c5cf98d5f6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L20-L29
