### ISSUE TITLE
Не полностью прописаны условия для ввода данных в конструкторе класса CreditAccount

### ISSUE THREAD

**Issue by GKZ28** [GKZ28/Java_Diplom#2]
# Описание
В конструкторе класса **CreditAccount** не указаны условия для проверки на неотрицательные значения всех параметров (**initialBalance**, **creditLimit** и **rate**).

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Предусловия
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Запустить программу

# Шаги воспроизведения
1. Создать объект класса **CreditAccount** cо значениями **rate** или **initialBalance** или **creditLimit**  равном или больше 0.
2. Создать объект класса **CreditAccount** cо значениями **rate** или **initialBalance** или **creditLimit**  меньше 0.

# Результаты
***Ожидаемый :*** 
"Конструктор создает аккаунт пользователя только при условии, что все данные неотрицательные, в ином случае должно срабатывать исключение **IllegalArgumentException**.

***Фактический :*** 
Конструктор проверяет только параметр **rate** на положительное значение, но не выполняет проверку для остальных параметров.

# Локация теста
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L10-L93

# Окружение
* **Операционная система.** Windows 11
*  **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Gamidov-M** [comment]
https://github.com/GKZ28/Java_Diplom/blob/c0039adbcd225eaa4b36e1cbb9d085c5cf98d5f6/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L10-L95
