### ISSUE TITLE
Не верно рассчитывается Баланс при выполнение метода pay в классе creditAccount.

### ISSUE THREAD

**Issue by GKZ28** [GKZ28/Java_Diplom#3]
# Описание
При выполнении метода **pay** и соблюдении условий, что итоговый баланс меньше кредитного лимита производится неправильный расчет итогового баланса.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L46

# Предусловия
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Запустить программу

# Шаги воспроизведения
1. Создать объект класса **CreditAccount** cо значениями **rate = 5** , **initialBalance = 10 000** или **creditLimit = 5000**.
2. Использовать метод **pay** cо значением 10000.

# Результаты
***Ожидаемый :*** 
При неположительном значении метод возвращает false. При положительном значении рассчитывает итоговый баланс. Если баланс больше лимита то возвращает false, если баланс меньше лимита, то проводит расчет по формуле **Баланс = Баланс - платеж**
Баланс должен равняться 0

***Фактический :*** 
Если баланс меньше лимита расчет производится некорректно.
Баланс равен -10000

# Локация теста
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L95-L128

# Окружение
* **Операционная система.** Windows 11
*  **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Gamidov-M** [comment]
Скорректировал код
https://github.com/GKZ28/Java_Diplom/blob/c0039adbcd225eaa4b36e1cbb9d085c5cf98d5f6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L42-L53
