### ISSUE TITLE
Не верно рассчитывается Баланс при выполнение метода add в классе creditAccount.

### ISSUE THREAD

**Issue by GKZ28** [GKZ28/Java_Diplom#4]
# Описание
При выполнении метода **add** и соблюдении условий, что сумма пополнения положительная производится неправильный расчет итогового баланса.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L69

# Предусловия
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Запустить программу

# Шаги воспроизведения
1. Создать объект класса **CreditAccount** cо значениями **rate = 15** , **initialBalance = 1 000** или **creditLimit = 5000**.
2. Использовать метод **add** cо значением 3000.

# Результаты
***Ожидаемый :*** 
При неположительном значении метод возвращает false. При положительном значении рассчитывает итоговый баланс по формуле **Баланс = Баланс + пополнение**
Баланс должен равняться 4000

***Фактический :*** 
Если платеж положительный расчет производится некорректно.
Баланс равен 3000

# Локация теста
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L130-L149

# Окружение
* **Операционная система.** Windows 11
*  **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Gamidov-M** [comment]
Ошибка крылась в строке balance = amount, нужен был код balance = balance + amount. Ошибка исправлена.
https://github.com/GKZ28/Java_Diplom/blob/c0039adbcd225eaa4b36e1cbb9d085c5cf98d5f6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L68-L75
