### ISSUE TITLE
Не верно прописаны условия выполнения метода yearChanger в классе creditAccount.

### ISSUE THREAD

**Issue by GKZ28** [GKZ28/Java_Diplom#5]
# Описание
При выполнении метода **yearChanger** не соблюдается условие, что баланс должен быть отрицательным.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Предусловия
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA
2. Запустить программу

# Шаги воспроизведения
1. Создать объект класса **CreditAccount** cо значениями **rate = 15** , **initialBalance = 1 000** или **creditLimit = 5000**.
2. Использовать метод **yearChanger**

# Результаты
***Ожидаемый :*** 
При неотрицательном значении баланса метод возвращает 0. При отрицательном значении рассчитывает итоговый процент по формуле **Баланс * rate / 100**
Процент должен равняться 0

***Фактический :*** 
Если баланс положительный расчет производится некорректно.
Баланс равен 150

# Локация теста
https://github.com/GKZ28/Java_Diplom/blob/dbe51006a2e72c94c57f5dcc47e351ca2ddba069/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L151-L167

# Окружение
* **Операционная система.** Windows 11
*  **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
*  **Java:** OpenJDK 11

**Comment by Gamidov-M** [comment]
Добавил условие 
https://github.com/GKZ28/Java_Diplom/blob/c0039adbcd225eaa4b36e1cbb9d085c5cf98d5f6/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L87-L93
