### ISSUE TITLE
Некорректный вывод баланса после пополнения меньше максимальной суммы

### ISSUE THREAD

**Issue by Gamidov-M** [GKZ28/Java_Diplom#8]
# Описание
При пополнении сумма баланса остаётся прежней, хотя максимальный лимит не превышается.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/a00f6ae47f9e15e4512fb464ddaf4c26f0b8ae5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/a00f6ae47f9e15e4512fb464ddaf4c26f0b8ae5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L67-L78) в IDEA.
2. Выставить значение переменной **initialBalance** (баланс) в 2000.
3. Выставить значение переменной **minBalance** (минимальный баланс) в 1000.
4. Выставить значение переменной **maxBalance** (максимальный баланс) в 10_000.
5. Выставить значение переменной **rate** (процентная ставка) в 5.
6. Выставить значение переменной **amount** (изменение баланса) в 3000.
7. Запустить тест.
8. Посмотреть на вывод в консоли.

*Ожидаемый результат:* баланс равен 5000.
*Фактический результат:* сумма баланса не изменилась (2000).

# Тестирование бага
https://github.com/GKZ28/Java_Diplom/blob/4e16ade3d788376c1b21877f01000d46a2e9d88b/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L8-L19

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by GKZ28** [comment]
Скорректировал код

https://github.com/GKZ28/Java_Diplom/blob/37b906cbc69c051b09dd5be40a37011bb3f79a67/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L68-L78
