### ISSUE TITLE
Производится расчёт процентов на отрицательный остаток счёта

### ISSUE THREAD

**Issue by Gamidov-M** [GKZ28/Java_Diplom#9]
# Описание
Производится расчёт процентов на отрицательный остаток счёта.

# Локация дефекта
https://github.com/GKZ28/Java_Diplom/blob/a00f6ae47f9e15e4512fb464ddaf4c26f0b8ae5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/GKZ28/Java_Diplom/blob/a00f6ae47f9e15e4512fb464ddaf4c26f0b8ae5a/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L87-L90) в IDEA.
2. Выставить значение переменной **initialBalance** (баланс) в -2000.
3. Выставить значение переменной **minBalance**(минимальный баланс) в 1000.
4. Выставить значение переменной **maxBalance** (максимальный баланс) в 10_000.
5 .Выставить значение переменной **rate** (процентная ставка) в 5.
6. Запустить тест.
7. Посмотреть на вывод в консоли.

*Ожидаемый результат:* проценты на остаток счёта равны 0.
*Фактический результат:* консоль выдаёт ответ -100.

# Тестирование бага
https://github.com/GKZ28/Java_Diplom/blob/4e16ade3d788376c1b21877f01000d46a2e9d88b/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L86-L97

# Окружение
* **Операционная система:** Windows 10
* **IDE:** IntelliJ IDEA 2023.1.2 (Community Edition)
* **Java:** OpenJDK 11

**Comment by GKZ28** [comment]
Добавил условие.

https://github.com/GKZ28/Java_Diplom/blob/37b906cbc69c051b09dd5be40a37011bb3f79a67/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L88-L92
